/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Treesitter */

#ifndef _Included_Treesitter
#define _Included_Treesitter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Treesitter
 * Method:    parserNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Treesitter_parserNew
  (JNIEnv *, jclass);

/*
 * Class:     Treesitter
 * Method:    parserDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Treesitter_parserDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Treesitter
 * Method:    queryNew
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_Treesitter_queryNew
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     Treesitter
 * Method:    queryDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Treesitter_queryDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Treesitter
 * Method:    queryCursorNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_Treesitter_queryCursorNew
  (JNIEnv *, jclass);

/*
 * Class:     Treesitter
 * Method:    queryCursorDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_Treesitter_queryCursorDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Treesitter
 * Method:    highlight
 * Signature: ([BIJJJ)[I
 */
JNIEXPORT jintArray JNICALL Java_Treesitter_highlight
  (JNIEnv *, jclass, jbyteArray, jint, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
